#!/usr/bin/env bash
# ============================================================================
# MoltChain Validator — Production Server Setup
# ============================================================================
#
# Run as root or with sudo on a fresh Debian/Ubuntu VPS.
#
# Usage:
#   sudo bash deploy/setup.sh testnet          # Setup for testnet
#   sudo bash deploy/setup.sh mainnet          # Setup for mainnet
#   sudo bash deploy/setup.sh testnet mainnet  # Setup for both networks
#
# This script:
#   1. Creates a 'moltchain' system user
#   2. Creates /etc/moltchain, /var/lib/moltchain, /var/log/moltchain
#   3. Copies binaries to /usr/local/bin
#   4. Generates /etc/moltchain/env with correct port assignments
#   5. Installs and enables the systemd service
#
# Port assignments (matching moltchain-start.sh / run-validator.sh V1):
#   Testnet: RPC=8899  WS=8900  P2P=7001  Signer=9201
#   Mainnet: RPC=9899  WS=9900  P2P=8001  Signer=9201
#
# ============================================================================

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/moltchain"
DATA_DIR="/var/lib/moltchain"
LOG_DIR="/var/log/moltchain"
USER="moltchain"
GROUP="moltchain"

# Parse network(s)
NETWORKS=()
for arg in "$@"; do
    case "$arg" in
        testnet|mainnet) NETWORKS+=("$arg") ;;
        *)
            echo "Usage: $0 <testnet|mainnet> [testnet|mainnet]"
            echo "Example: $0 testnet          # Setup testnet only"
            echo "         $0 testnet mainnet   # Setup both"
            exit 1
            ;;
    esac
done

if [ ${#NETWORKS[@]} -eq 0 ]; then
    echo "Usage: $0 <testnet|mainnet> [testnet|mainnet]"
    exit 1
fi

echo "=== MoltChain Validator Setup ==="
echo "Networks: ${NETWORKS[*]}"
echo ""

# ── 1. Create system user ──
if ! id -u "$USER" &>/dev/null; then
    groupadd -r "$GROUP"
    useradd -r -g "$GROUP" -d /home/"$USER" -m -s /bin/false "$USER"
    echo "✅ Created system user: $USER"
else
    echo "✅ System user $USER already exists"
fi

# ── 2. Create directories ──
mkdir -p "$CONFIG_DIR" "$DATA_DIR" "$LOG_DIR"
chown "$USER":"$GROUP" "$DATA_DIR" "$LOG_DIR"
echo "✅ Directories created"

# ── 3. Copy binaries ──
for bin in moltchain-validator molt moltchain-faucet; do
    if [ -f "target/release/$bin" ]; then
        cp "target/release/$bin" "$INSTALL_DIR/$bin"
        chmod +x "$INSTALL_DIR/$bin"
        echo "   Installed: $bin → $INSTALL_DIR"
    else
        echo "   ⚠  $bin not found in target/release/ (skipping)"
    fi
done

# ── 4. Generate env file + install systemd per network ──
for net in "${NETWORKS[@]}"; do
    echo ""
    echo "--- Setting up $net ---"

    case $net in
        testnet)
            RPC_PORT=8899; WS_PORT=8900; P2P_PORT=7001; SIGNER_PORT=9201
            ;;
        mainnet)
            RPC_PORT=9899; WS_PORT=9900; P2P_PORT=8001; SIGNER_PORT=9201
            ;;
    esac

    ENV_FILE="$CONFIG_DIR/env-${net}"
    cat > "$ENV_FILE" <<EOF
# MoltChain $net environment — auto-generated by deploy/setup.sh
MOLTCHAIN_NETWORK=$net
MOLTCHAIN_RPC_PORT=$RPC_PORT
MOLTCHAIN_WS_PORT=$WS_PORT
MOLTCHAIN_P2P_PORT=$P2P_PORT
# P9-INF-09: Custody signer binds to loopback only (not all interfaces)
MOLTCHAIN_SIGNER_BIND=127.0.0.1:$SIGNER_PORT
RUST_LOG=info
# MOLTCHAIN_ADMIN_TOKEN=your-secret-token-here
EOF
    chmod 600 "$ENV_FILE"
    echo "   ✅ Created $ENV_FILE"

    # Create network-specific state dir
    mkdir -p "$DATA_DIR/state-${net}"
    chown "$USER":"$GROUP" "$DATA_DIR/state-${net}"

    # Install network-specific systemd service
    SERVICE_NAME="moltchain-validator-${net}"
    SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

    sed "s|EnvironmentFile=/etc/moltchain/env|EnvironmentFile=/etc/moltchain/env-${net}|" \
        deploy/moltchain-validator.service > "$SERVICE_FILE"

    # Update SyslogIdentifier for this network
    sed -i "s|SyslogIdentifier=moltchain-validator|SyslogIdentifier=${SERVICE_NAME}|" \
        "$SERVICE_FILE"

    systemctl daemon-reload
    echo "   ✅ Installed systemd service: $SERVICE_NAME"
    echo "   Start:  sudo systemctl start $SERVICE_NAME"
    echo "   Enable: sudo systemctl enable $SERVICE_NAME"
    echo "   Logs:   journalctl -u $SERVICE_NAME -f"
done

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Quick reference:"
for net in "${NETWORKS[@]}"; do
    case $net in
        testnet) echo "  $net → RPC :8899  WS :8900  P2P :7001" ;;
        mainnet) echo "  $net → RPC :9899  WS :9900  P2P :8001" ;;
    esac
done
echo ""
echo "Firewall (if using ufw):"
for net in "${NETWORKS[@]}"; do
    case $net in
        testnet) echo "  sudo ufw allow 7001/tcp  # testnet P2P" ;;
        mainnet) echo "  sudo ufw allow 8001/tcp  # mainnet P2P" ;;
    esac
done
echo ""
echo "⚠  First boot: the first validator on a network creates genesis automatically."
echo "   Genesis keys (treasury) will be in: $DATA_DIR/state-<network>/genesis-keys/"
echo "   Keep those keys secure — they control the 1B MOLT treasury."
