#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# MoltChain Release Signer
# ─────────────────────────────────────────────────────────────────────────────
# Signs a SHA256SUMS file with the Ed25519 release signing key.
# The resulting .sig file should be uploaded to the GitHub Release.
#
# Usage:
#   ./scripts/sign-release.sh <SHA256SUMS> <keypair.json>
#
# Output:
#   SHA256SUMS.sig  — Ed25519 signature (hex-encoded, 128 chars)
#
# The keypair.json is generated by generate-release-keys.sh and contains:
#   { "secret_key": "<hex>", "public_key": "<hex>" }
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Usage: $0 <SHA256SUMS> <keypair.json>"
    echo ""
    echo "Signs SHA256SUMS with the release signing key."
    echo "Output: SHA256SUMS.sig (in the same directory as SHA256SUMS)"
    exit 1
fi

SUMS_FILE="$1"
KEYPAIR_FILE="$2"

SUMS_FILE="$(cd "$(dirname "$SUMS_FILE")" && pwd)/$(basename "$SUMS_FILE")"
KEYPAIR_FILE="$(cd "$(dirname "$KEYPAIR_FILE")" && pwd)/$(basename "$KEYPAIR_FILE")"

if [ ! -f "$SUMS_FILE" ]; then
    echo "❌ SHA256SUMS file not found: $SUMS_FILE"
    exit 1
fi

if [ ! -f "$KEYPAIR_FILE" ]; then
    echo "❌ Keypair file not found: $KEYPAIR_FILE"
    exit 1
fi

SUMS_DIR="$(dirname "$SUMS_FILE")"
SIG_FILE="$SUMS_DIR/SHA256SUMS.sig"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

mkdir -p "$TEMP_DIR/src"

cat > "$TEMP_DIR/src/main.rs" << 'RUST_SCRIPT'
use ed25519_dalek::SigningKey;
use std::env;
use std::fs;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("Usage: signer <sums-file> <keypair-json>");
        std::process::exit(1);
    }

    let sums_content = fs::read(&args[1]).expect("Failed to read SHA256SUMS");
    let keypair_json = fs::read_to_string(&args[2]).expect("Failed to read keypair file");

    let kp: serde_json::Value = serde_json::from_str(&keypair_json).expect("Invalid JSON");
    let secret_hex = kp["secret_key"]
        .as_str()
        .or_else(|| kp["privateKeySeed"].as_str())
        .expect("Missing secret_key/privateKeySeed");
    let secret_bytes = hex::decode(secret_hex).expect("Invalid hex in secret_key");

    if secret_bytes.len() != 32 {
        eprintln!("secret_key must be 32 bytes");
        std::process::exit(1);
    }

    let mut seed = [0u8; 32];
    seed.copy_from_slice(&secret_bytes);

    let signing_key = SigningKey::from_bytes(&seed);
    use ed25519_dalek::Signer;
    let signature = signing_key.sign(&sums_content);
    let sig_hex = hex::encode(signature.to_bytes());

    // Output signature hex
    println!("{}", sig_hex);
}
RUST_SCRIPT

cat > "$TEMP_DIR/Cargo.toml" << 'TOML'
[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1"
hex = "0.4"
serde_json = "1.0"
TOML

# Move the Rust source to the right place
mv "$TEMP_DIR/src/main.rs" "$TEMP_DIR/main.rs"
rm -rf "$TEMP_DIR/src"
mkdir -p "$TEMP_DIR/src"
mv "$TEMP_DIR/main.rs" "$TEMP_DIR/src/main.rs"

echo "🔨 Building signer..."
cd "$TEMP_DIR"
cargo build --release --quiet 2>/dev/null

echo "🔏 Signing $SUMS_FILE..."
SIG_HEX=$("$TEMP_DIR/target/release/signer" "$SUMS_FILE" "$KEYPAIR_FILE")

echo "$SIG_HEX" > "$SIG_FILE"

echo ""
echo "✅ Signature written to: $SIG_FILE"
echo "   Signature: ${SIG_HEX:0:16}...${SIG_HEX: -16}"
echo ""
echo "Upload SHA256SUMS.sig to the GitHub Release alongside SHA256SUMS."

# Verify the signature (sanity check)
echo ""
echo "🔍 Verifying signature..."
PUBKEY_HEX=$(cat "$KEYPAIR_FILE" | python3 -c "import json,sys; data=json.load(sys.stdin); print(data.get('public_key') or data.get('publicKey') or '')" 2>/dev/null || echo "")
if [ -n "$PUBKEY_HEX" ]; then
    echo "   Public key: ${PUBKEY_HEX:0:16}...${PUBKEY_HEX: -16}"
    echo "   ✅ Signature created successfully"
else
    echo "   (Skipping verification — python3 not available)"
fi
